/** Route path constants — single source for router and navigation. */
export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  terms: '/terms',
  profile: '/profile',
  players: '/players',
  playerProfile: '/players/:userId',
  teams: '/teams',
  events: '/events',
  trainingDetails: '/events/trainings/:eventId',
  calendar: '/calendar',
  sos: '/sos',
  arenas: '/arenas',
  leagues: '/leagues',
  feedback: '/feedback',
  notifications: '/notifications',
  messenger: '/messenger',
  shops: '/shops',
  partner: '/partner',
  partnerShop: '/partner/shops/:shopId',
  partnerLeague: '/partner/leagues/:leagueId',
  iq: '/iq',
  radar: '/radar',
  highlights: '/highlights',
  admin: '/admin',
} as const
